### ISSUE TITLE
XGBoost Assertion error

### ISSUE THREAD

**Issue by dfousek** [madagra/energy-ts-analysis#2]
Hi !
I was trying to re-run your excellent example forecast.ipynb in Google Colab and I am getting the above error.
I used Colab, as installing prophet, xgboost in windows isn't well supported.
What's the meaning of the error?
Kind regards,
Dimitri

**Comment by madagra** [comment]
Hi Dimitri,

I am sorry for the (very) late answer to this, I did not have much time to follow this repository lately. Anyway, if this is still relevant for your, can you please post here the log of the exact error you get? If you use Google Colab there shouldn't be any issue in installing `xgboost` since I've done that in the past. Thanks!
